apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort // access via minikube service user-service or localhost:<nodePort>
  # type: ClusterIP // ClusterIP accessible only inside cluster
